-- MySQL Script generated by MySQL Workbench
-- mié 16 nov 2022 22:45:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema product_manager
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `product_manager` ;

-- -----------------------------------------------------
-- Schema product_manager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `product_manager` ;
USE `product_manager` ;

-- -----------------------------------------------------
-- Table `product_manager`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product_manager`.`categories` ;

CREATE TABLE IF NOT EXISTS `product_manager`.`categories` (
  `idcategory` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(50) NOT NULL,
  `date_created` DATETIME NOT NULL,
  `user_created` VARCHAR(45) NOT NULL,
  `date_updated` DATETIME NOT NULL,
  `user_updated` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategory`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `product_manager`.`brands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product_manager`.`brands` ;

CREATE TABLE IF NOT EXISTS `product_manager`.`brands` (
  `idbrand` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(50) NULL DEFAULT NULL,
  `date_created` DATETIME NOT NULL,
  `user_created` VARCHAR(45) NOT NULL,
  `date_updated` DATETIME NOT NULL,
  `user_updated` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idbrand`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `product_manager`.`units`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product_manager`.`units` ;

CREATE TABLE IF NOT EXISTS `product_manager`.`units` (
  `idunit` INT NOT NULL AUTO_INCREMENT,
  `unit_code` CHAR(6) NOT NULL,
  `description` VARCHAR(50) NOT NULL,
  `date_created` DATETIME NOT NULL,
  `user_created` VARCHAR(45) NOT NULL,
  `date_updated` DATETIME NOT NULL,
  `user_updated` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idunit`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `product_manager`.`unit_equivalence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product_manager`.`unit_equivalence` ;

CREATE TABLE IF NOT EXISTS `product_manager`.`unit_equivalence` (
  `idunit_equivalence` INT NOT NULL AUTO_INCREMENT,
  `base_unit` INT NOT NULL,
  `des_unit` INT NOT NULL,
  `multiple_quantity` SMALLINT NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `start_validity` DATETIME NOT NULL,
  `end_validity` DATETIME NOT NULL,
  `status` CHAR(1) NOT NULL DEFAULT 'A',
  PRIMARY KEY (`idunit_equivalence`),
  INDEX `f_unit_equivalence1` (`base_unit` ASC) VISIBLE,
  INDEX `f_unit_equivalence2` (`des_unit` ASC) VISIBLE,
  CONSTRAINT `f_unit_equivalence1`
    FOREIGN KEY (`base_unit`)
    REFERENCES `product_manager`.`units` (`idunit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `f_unit_equivalence2`
    FOREIGN KEY (`des_unit`)
    REFERENCES `product_manager`.`units` (`idunit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `product_manager`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product_manager`.`products` ;

CREATE TABLE IF NOT EXISTS `product_manager`.`products` (
  `idproduct` INT NOT NULL AUTO_INCREMENT,
  `product` VARCHAR(255) NOT NULL,
  `idunit` INT NOT NULL,
  `idcategory` INT NOT NULL,
  `idbrand` INT NOT NULL,
  `filename` MEDIUMTEXT NULL DEFAULT NULL,
  `origen_web` MEDIUMTEXT NULL DEFAULT NULL,
  `date_created` DATETIME NOT NULL,
  `user_created` VARCHAR(45) NOT NULL,
  `date_updated` DATETIME NOT NULL,
  `user_updated` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproduct`),
  INDEX `f_products1_idx` (`idunit` ASC) VISIBLE,
  INDEX `f_products2_idx` (`idcategory` ASC) VISIBLE,
  INDEX `f_products4_idx` (`idbrand` ASC) VISIBLE,
  CONSTRAINT `f_products1`
    FOREIGN KEY (`idunit`)
    REFERENCES `product_manager`.`units` (`idunit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `f_products2`
    FOREIGN KEY (`idcategory`)
    REFERENCES `product_manager`.`categories` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `f_products4`
    FOREIGN KEY (`idbrand`)
    REFERENCES `product_manager`.`brands` (`idbrand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `product_manager`.`warehouse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product_manager`.`warehouse` ;

CREATE TABLE IF NOT EXISTS `product_manager`.`warehouse` (
  `idwarehouse` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(50) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `date_low` DATETIME NULL DEFAULT NULL,
  `date_created` DATETIME NOT NULL,
  `user_created` VARCHAR(45) NOT NULL,
  `date_updated` DATETIME NOT NULL,
  `user_updated` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idwarehouse`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `product_manager`.`items_warehouse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product_manager`.`items_warehouse` ;

CREATE TABLE IF NOT EXISTS `product_manager`.`items_warehouse` (
  `idwarehouse` INT NOT NULL,
  `idproduct` INT NOT NULL,
  `logistic_variable` SMALLINT NOT NULL,
  `stock` SMALLINT NOT NULL,
  `idunit` INT NOT NULL,
  `expiration_date` DATE NULL DEFAULT NULL,
  `date_created` DATETIME NOT NULL,
  `user_created` VARCHAR(45) NOT NULL,
  `date_updated` DATETIME NOT NULL,
  `user_updated` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idwarehouse`),
  INDEX `i_items_warehouse1` (`idproduct` DESC) VISIBLE,
  INDEX `f_items_warehouse3` (`idunit` ASC) VISIBLE,
  CONSTRAINT `f_items_warehouse1`
    FOREIGN KEY (`idwarehouse`)
    REFERENCES `product_manager`.`warehouse` (`idwarehouse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `f_items_warehouse2`
    FOREIGN KEY (`idproduct`)
    REFERENCES `product_manager`.`products` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `f_items_warehouse3`
    FOREIGN KEY (`idunit`)
    REFERENCES `product_manager`.`units` (`idunit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
